/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 enigma.gltf -t 
Author: ASHISH (https://sketchfab.com/3dmodelsmith)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/enigma-machine-30b85c037a164174a109ad6f002b9c47
Title: Enigma Machine
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    part001_low_low_mec002_0: THREE.Mesh
    part004_low_low_mec002_0: THREE.Mesh
    part005_low_low_mec002_0: THREE.Mesh
    part006_low_low_mec002_0: THREE.Mesh
    part008_low_low_mec002_0: THREE.Mesh
    part009_low_low_mec002_0: THREE.Mesh
    part010_low_low_mec002_0: THREE.Mesh
    part011_low_low_mec002_0: THREE.Mesh
    part012_low_low_mec002_0: THREE.Mesh
    part013_low_low_mec002_0: THREE.Mesh
    part014_low_low_mec002_0: THREE.Mesh
    part015_low_low_mec002_0: THREE.Mesh
    part016_low_low_mec002_0: THREE.Mesh
    part017_low_low_mec002_0: THREE.Mesh
    part018_low_low_mec002_0: THREE.Mesh
    part020_low_low_mec002_0: THREE.Mesh
    part021_low_low_mec002_0: THREE.Mesh
    part022_low_low_mec002_0: THREE.Mesh
    part029_low_low_mec002_0: THREE.Mesh
    part030_low_low_mec002_0: THREE.Mesh
    part031_low_low_mec002_0: THREE.Mesh
    part032_low_low_mec002_0: THREE.Mesh
    part033_low_low_mec002_0: THREE.Mesh
    part034_low_low_mec002_0: THREE.Mesh
    part045_low_low_mec002_0: THREE.Mesh
    part046_low_low_mec002_0: THREE.Mesh
    part047_low_low_mec002_0: THREE.Mesh
    part048_low_low_mec002_0: THREE.Mesh
    part049_low_low_mec002_0: THREE.Mesh
    part050_low_low_mec002_0: THREE.Mesh
    part051_low_low_mec002_0: THREE.Mesh
    part052_low_low_mec002_0: THREE.Mesh
    part053_low_low_mec002_0: THREE.Mesh
    part054_low_low_mec002_0: THREE.Mesh
    part060_low_w2_low_mec_0: THREE.Mesh
    part067_low_low_mec002_0: THREE.Mesh
    part072_low_low_mec002_0: THREE.Mesh
    part073_low_low_mec002_0: THREE.Mesh
    part074_low_low_mec002_0: THREE.Mesh
    part075_low_low_mec002_0: THREE.Mesh
    part076_low_low_mec002_0: THREE.Mesh
    part086_low_low_mec002_0: THREE.Mesh
    part078_low_low_box001_0: THREE.Mesh
    part077_low_low_box001_0: THREE.Mesh
    part035_low_low_box001_0: THREE.Mesh
    part003_low_low_box001_0: THREE.Mesh
    part037_low_low_box001_0: THREE.Mesh
    part038_low_low_box001_0: THREE.Mesh
    part036_low_low_box001_0: THREE.Mesh
    part023_low_low_box001_0: THREE.Mesh
    part056_low_w1_low_box_0: THREE.Mesh
    part044_low_low_box001_0: THREE.Mesh
    part040_low_low_box001_0: THREE.Mesh
    part039_low_low_box001_0: THREE.Mesh
    part041_low_low_box001_0: THREE.Mesh
    part042_low_low_box001_0: THREE.Mesh
    part043_low_low_box001_0: THREE.Mesh
    part079_low_low_box001_0: THREE.Mesh
    part080_low_low_box001_0: THREE.Mesh
    part081_low_low_box001_0: THREE.Mesh
    part007_low_low_box001_0: THREE.Mesh
    part002_low_low_box001_0: THREE.Mesh
    part019_low_low_box001_0: THREE.Mesh
    part069_low_low_box001_0: THREE.Mesh
    part071_low_low_box001_0: THREE.Mesh
    part070_low_low_box001_0: THREE.Mesh
    part082_low_low_box001_0: THREE.Mesh
    part024_low_low_box001_0: THREE.Mesh
    part084_low_low_box001_0: THREE.Mesh
    part083_low_low_box001_0: THREE.Mesh
    part085_low_low_box001_0: THREE.Mesh
    part028_low_low_box001_0: THREE.Mesh
    part025_low_low_box001_0: THREE.Mesh
    part027_low_low_box001_0: THREE.Mesh
    part068_low_low_box001_0: THREE.Mesh
    part_low_low_box001_0: THREE.Mesh
    part066_low_low_box001_0: THREE.Mesh
    part026_low_low_box001_0: THREE.Mesh
    part087_low_glass_0: THREE.Mesh
  }
  materials: {
    ['low_mec.002']: THREE.MeshStandardMaterial
    w2_low_mec: THREE.MeshStandardMaterial
    ['low_box.001']: THREE.MeshStandardMaterial
    w1_low_box: THREE.MeshStandardMaterial
    glass: THREE.MeshPhysicalMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/enigma.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.576, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.part001_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.298, 0, 9.668]} scale={100} />
          <mesh geometry={nodes.part004_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-8.352, 0, 8.84]} scale={100} />
          <mesh geometry={nodes.part005_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.73, 0, 11.292]} scale={100} />
          <mesh geometry={nodes.part006_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-8.493, 0.005, 10.407]} scale={100} />
          <mesh geometry={nodes.part008_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-13.307, 0, 5.496]} scale={100} />
          <mesh geometry={nodes.part009_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[9.837, 1.92, 12.457]} scale={100} />
          <mesh geometry={nodes.part010_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[0.875, -0.313, 12.18]} scale={100} />
          <mesh geometry={nodes.part011_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[8.523, -0.169, 12.631]} scale={100} />
          <mesh geometry={nodes.part012_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-10.421, -9.889, 9.404]} scale={100} />
          <mesh geometry={nodes.part013_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-4.977, -10.442, 10.279]} scale={100} />
          <mesh geometry={nodes.part014_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-7.742, -9.049, 9.863]} scale={100} />
          <mesh geometry={nodes.part015_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[14.77, 1.92, 12.595]} scale={100} />
          <mesh geometry={nodes.part016_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[8.524, 2.72, 12.247]} scale={100} />
          <mesh geometry={nodes.part017_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[14.144, 1.923, 12.773]} scale={100} />
          <mesh geometry={nodes.part018_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-1.212, 0, 12.802]} scale={100} />
          <mesh geometry={nodes.part020_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-13.622, 0, 5.815]} scale={100} />
          <mesh geometry={nodes.part021_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[14.144, 1.923, 12.773]} scale={100} />
          <mesh geometry={nodes.part022_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[14.144, 1.923, 12.773]} scale={100} />
          <mesh geometry={nodes.part029_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[1.622, 0, 12.699]} scale={100} />
          <mesh geometry={nodes.part030_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[1.622, 0, 13.143]} scale={100} />
          <mesh geometry={nodes.part031_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[1.622, -11.747, 12.719]} scale={100} />
          <mesh geometry={nodes.part032_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[5.14, 1.919, 12.687]} scale={100} />
          <mesh geometry={nodes.part033_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.026, 1.919, 13.122]} scale={100} />
          <mesh geometry={nodes.part034_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[5.606, -3.199, 12.69]} scale={100} />
          <mesh geometry={nodes.part045_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.39, -6.976, 12.418]} scale={100} />
          <mesh geometry={nodes.part046_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[5.206, 0, 12.61]} scale={100} />
          <mesh geometry={nodes.part047_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[5.206, 0, 13.109]} scale={100} />
          <mesh geometry={nodes.part048_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.454, 0, 13.68]} scale={100} />
          <mesh geometry={nodes.part049_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.543, -11.937, 13.751]} scale={100} />
          <mesh geometry={nodes.part050_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[7.705, -0.001, 12.61]} scale={100} />
          <mesh geometry={nodes.part051_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[7.705, -11.977, 12.738]} scale={100} />
          <mesh geometry={nodes.part052_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.39, -6.976, 12.451]} scale={100} />
          <mesh geometry={nodes.part053_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[6.39, -6.976, 13.265]} scale={100} />
          <mesh geometry={nodes.part054_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-14.3, 0.014, 5.677]} scale={100} />
          <mesh geometry={nodes.part060_low_w2_low_mec_0.geometry} material={materials.w2_low_mec} position={[-14.626, -8.055, 4.815]} scale={100} />
          <mesh geometry={nodes.part067_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-12.253, 0, 10.144]} scale={100} />
          <mesh geometry={nodes.part072_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[13.734, 1.678, 12.725]} scale={100} />
          <mesh geometry={nodes.part073_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[14.588, 2.086, 12.725]} scale={100} />
          <mesh geometry={nodes.part074_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[8.525, 2.787, 12.689]} scale={100} />
          <mesh geometry={nodes.part075_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-12.253, 0, 10.258]} scale={100} />
          <mesh geometry={nodes.part076_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-13.446, -12.852, 5.668]} scale={100} />
          <mesh geometry={nodes.part086_low_low_mec002_0.geometry} material={materials['low_mec.002']} position={[-13.27, -5.385, 3.349]} scale={100} />
          <mesh geometry={nodes.part078_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part077_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part035_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.823, 0, 43.453]} scale={100} />
          <mesh geometry={nodes.part003_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.219, 0, 44.249]} scale={100} />
          <mesh geometry={nodes.part037_low_low_box001_0.geometry} material={materials['low_box.001']} position={[21.972, 0, 33.663]} scale={100} />
          <mesh geometry={nodes.part038_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.576, 0, 33.663]} scale={100} />
          <mesh geometry={nodes.part036_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.536, 0, 33.663]} scale={100} />
          <mesh geometry={nodes.part023_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0.001, 15.069]} scale={100} />
          <mesh geometry={nodes.part056_low_w1_low_box_0.geometry} material={materials.w1_low_box} position={[22.133, -9.685, 14.308]} scale={100} />
          <mesh geometry={nodes.part044_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.604, 0, 14.835]} scale={100} />
          <mesh geometry={nodes.part040_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0, 15.152]} scale={100} />
          <mesh geometry={nodes.part039_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0, 15.152]} scale={100} />
          <mesh geometry={nodes.part041_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0, 15.072]} scale={100} />
          <mesh geometry={nodes.part042_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0, 15.074]} scale={100} />
          <mesh geometry={nodes.part043_low_low_box001_0.geometry} material={materials['low_box.001']} position={[22.132, 0, 15.074]} scale={100} />
          <mesh geometry={nodes.part079_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part080_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part081_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part007_low_low_box001_0.geometry} material={materials['low_box.001']} position={[18.616, -0.014, 6.627]} scale={100} />
          <mesh geometry={nodes.part002_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.77, 0, 6.627]} scale={100} />
          <mesh geometry={nodes.part019_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part069_low_low_box001_0.geometry} material={materials['low_box.001']} position={[15.645, 0, 15.855]} scale={100} />
          <mesh geometry={nodes.part071_low_low_box001_0.geometry} material={materials['low_box.001']} position={[13.093, 0, 13.795]} scale={100} />
          <mesh geometry={nodes.part070_low_low_box001_0.geometry} material={materials['low_box.001']} position={[11.422, 0, 11.45]} scale={100} />
          <mesh geometry={nodes.part082_low_low_box001_0.geometry} material={materials['low_box.001']} position={[17.5, 0, 9.694]} scale={100} />
          <mesh geometry={nodes.part024_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-16.821, 0.566, -8.073]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part084_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-17.214, -1.048, -8.073]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part083_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-17.137, 0, -0.008]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part085_low_low_box001_0.geometry} material={materials['low_box.001']} scale={100} />
          <mesh geometry={nodes.part028_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-17.137, 0, -0.008]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part025_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-17.137, 0, -0.008]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part027_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-17.137, 0, -0.008]} scale={100} />
          <mesh geometry={nodes.part068_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-14.829, 0, 8.873]} scale={100} />
          <mesh geometry={nodes.part_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-18.22, 0, -8.754]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part066_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-15.459, 0, 6.71]} scale={100} />
          <mesh geometry={nodes.part026_low_low_box001_0.geometry} material={materials['low_box.001']} position={[-18.645, 0, -6.726]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.part087_low_glass_0.geometry} material={materials.glass} position={[8.545, 2.715, 12.578]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/enigma.gltf')
